test(RHTAPWATCH-1066): Unit tests for getWorkspacesWithAccess
konflux-ci/workspace-manager pull request #50
Opened 2024-07-30 20:19 UTC by hmariset

Add unit test for workspace-manager function
getWorkspacesWithAccess

Jira-Url: https://issues.redhat.com/browse/RHTAPWATCH-1066

2024-07-30 20:22 UTC, hmariset commented
@Omeramsc, @avi-biton  Please review the PR.

2024-08-01 09:29 UTC, Omeramsc requested changes

2024-08-01 09:29 UTC, Omeramsc commented on cmd/main_test.go
> +			createRoleBinding(k8sClient, "namespace-access-user-binding-2", "test-tenant", "user2@konflux.dev", "namespace-access")
You can add those assignments to the loop

2024-08-01 09:29 UTC, Omeramsc commented on cmd/main_test.go
> +			createRoleBinding(k8sClient, "namespace-access-user-binding", "test-tenant", "user1@konflux.dev", "namespace-access")
Is it relevant for this test to have both user1 and user2?

2024-08-01 09:29 UTC, Omeramsc commented on cmd/main_test.go
> +		It("WorkspaceList should be created with ns1 and ns2 names", func() {
Let's try rephrasing it a tiny bit to make the schema more readable
something similar to this:
  Describe("GetWorkspacesWithAccess querying for workspaces with access"  ) {
Context("When workspace "test-tenant"'s namespaces has  all the necessary permissions",) { 
It("Should return a WorkspaceList with test-tenant workspace and ns1 and ns2 in it")

2024-08-01 09:29 UTC, Omeramsc commented on cmd/main_test.go
> +		It("WorkspaceList should be created with ns1 and ns2 names", func() {
(same for the rest of the tests)

2024-08-01 09:29 UTC, Omeramsc commented on cmd/main_test.go
> +})
Add a case of no workspaces returned

2024-08-04 08:27 UTC, Omeramsc requested changes
Good progress, please add cleanup after the unit tests.

2024-08-04 08:27 UTC, Omeramsc commented on cmd/main_test.go
> +				createRoleBinding(k8sClient, "namespace-access-user-binding", name, "user1@konflux.dev", "namespace-access")
Those two lines should result in an error, as a resource with this name ( "namespace-access-user-binding", "namespace-access") already exists (as you are creating them for two namespaces). if it did not error, check out why. 

after you see why, you can use an index to create it in the loop.

2024-08-04 08:27 UTC, Omeramsc commented on cmd/main_test.go
> +			namespaceNames := []string{"test-tenant", "test-tenant-3"}
why are we using test-tenant-3 and not 2?

2024-08-04 08:27 UTC, Omeramsc commented on cmd/main_test.go
> +			createRole(k8sClient, "test-tenant", "namespace-access", []string{"create", "list", "watch", "delete"})
as we did not clean up the previous test, this should fail as we create the same resource twice.

2024-08-04 08:27 UTC, Omeramsc commented on cmd/main_test.go
> +			createRoleBinding(k8sClient, "namespace-access-user-binding", "test-tenant", "user1@konflux.dev", "namespace-access")
As we did not clean up the previous test, how can we know this does not clash with the roles we binded to this namespace in the previous test?

2024-08-04 08:27 UTC, Omeramsc commented on cmd/main_test.go
> +			createRoleBinding(k8sClient, "namespace-access-user-binding-3", "test-tenant-3", "user1@konflux.dev", "namespace-access")
I don't get it, we gave test-tenant and test-tenant-3 the same roles and permissions, why does the test return only test-tenant in the workspace?

2024-08-04 08:27 UTC, Omeramsc commented on cmd/main_test.go
> +			expectedWorkspaces = []crt.Workspace{}
I'm not sure how that is the result we are getting, taking into considiration we did not clean up the resources we created on the other test cases

2024-08-06 09:36 UTC, Omeramsc requested changes
resource managment between tests require fixing.

Also if my comments are not about typos/basic syntax, please comment on them with how you fixed them before resolving them (or wait for my resolution).

2024-08-06 09:36 UTC, Omeramsc commented on cmd/main_test.go
> +			allNamespaces = []k8sapi.Namespace{}
Those are not the variables you need to clean, 
what we need to clean are the actual resources.

for example:
in the test you ran the following- 
```
createNamespace(k8sClient, name)
createRole(k8sClient, name, "namespace-access", []string{"create", "list", "watch", "delete"})
createRoleBinding(k8sClient, "namespace-access-user-binding", name, "user1@konflux.dev", "namespace-access")
```

those resources may stay available on the envtest cluster while the other tests are running, as we use the same env. we should remove all resources we created.

2024-08-11 08:52 UTC, Omeramsc approved these changes
LGTM

2024-08-11 09:15 UTC, merged